### ISSUE TITLE
Business Hours on Store site

### ISSUE THREAD

**Issue by GinaDoherty** [familiar-studio/UrbanGlass-Shopify#1]
So at the moment we have our hours listed on the store site as until 7pm. I went to change it to be 7:30pm, but it only allows us every hour (see below). Is there a workaround for this?

![image](https://user-images.githubusercontent.com/22894938/27883872-236a2e4a-61a0-11e7-9a11-da35830e9c6c.png)

https://app.intercom.io/a/apps/aadhbcv9/respond/inbox/792234/conversations/10654921099

**Comment by davefischoff** [comment]
@brianbier - i'm wondering if there's a setting in Shopify that would allow them to show half hours?

**Comment by davefischoff** [comment]
@keithmancuso - brian and I have both looked for a setting in Shopify that will allow them to show half-hours, but can't find one. Do you know if this is possible?

**Comment by keithmancuso** [comment]
hey @GinaDoherty finally got around to doing this one, it should just be a fil in now instead of a dropin so they should be able to write whatever they want!
